# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      copr:
        - atim/starship
    install:
      packages:
        - fish
        - starship
        - micro
        - tealdeer
        - gnome-shell-extension-gsconnect

    remove:
      packages:
        - gnome-system-monitor 
        - firefox
        - firefox-langpacks

  - type: gnome-extensions
    install:
      - 7065    # Tilling Shell
      - 3193    # Blur my Shell
      - 6281    # Wallpaper Slideshow
      - 779     # Clipboard Indicator
      - 615     # AppIndicator and KStatusNotifierItem Support
      - 6670    # Bluetooth Battery Meter
      # - 1319    # GSConnect
      - 517     # Caffeine
      - 4269    # Alphabetical App Grid

  - type: bling
    install:
      - dconf-update-service

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - app.zen_browser.zen
          - io.missioncenter.MissionCenter
          - com.github.johnfactotum.Foliate
          - org.videolan.VLC
          - com.mattjakeman.ExtensionManager
          - com.github.tchx84.Flatseal
        remove:
          - org.gnome.Extensions
      - scope: user # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully