---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: Ciri
# description will be included in the image's metadata
description: A custom u-blue image with opiniated packages and settings.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - micro
    remove:
      - gnome-system-monitor 
      - firefox
      - firefox-langpacks

  - type: gnome-extensions
    install:
      - Tilling Shell
      - Blur my Shell
      - Wallpaper Slideshow
      - Clipboard Indicator
      - AppIndicator and KStatusNotifierItem Support
      - Bluetooth Battery Meter
      - GSConnect
      - Caffeine
      - Alphabetical App Grid

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - app.zen_browser.zen
          - io.missioncenter.MissionCenter
          - com.github.johnfactotum.Foliate
          - org.videolan.VLC
      - scope: user # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

